sudo: required
services:
  - docker

before_install:
  - docker build -t elvito/complex-client-test -f ./client/Dockerfile.dev ./client #run tests

scripts:
  - docker run -e CI=true elvito/complex-client-test npm test #coverage makes it exits 

after_success:
  - docker build -t elvito2121/multi-client ./client 
  - docker build -t elvito2121/multi-nginx ./nginx 
  - docker build -t elvito2121/multi-server ./server 
  - docker build -t elvito2121/multi-worker ./worker 
  # LOGIN in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push elvito2121/multi-client
  - docker push elvito2121/multi-nginx
  - docker push elvito2121/multi-server
  - docker push elvito2121/multi-worker